run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gofmt
    - goimports
    - prealloc

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/krishna-kudari/ratelimit

issues:
  exclude-dirs:
    - vendor
    - examples/demo/static
  max-issues-per-linter: 50
  max-same-issues: 5
