# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.v1.jsonschema.json
run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gofmt
    - goimports

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/krishna-kudari/ratelimit

issues:
  exclude-dirs:
    - vendor
    - examples/demo/static
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: example_test\.go
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 5
