name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue.
      render: go
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: go1.25.0 darwin/arm64
    validations:
      required: true

  - type: dropdown
    id: backend
    attributes:
      label: Backend
      options:
        - In-memory
        - Redis (standalone)
        - Redis (Cluster)
        - Redis (Ring)
        - Redis (Sentinel)
    validations:
      required: true

  - type: dropdown
    id: algorithm
    attributes:
      label: Algorithm
      options:
        - Fixed Window
        - Sliding Window Log
        - Sliding Window Counter
        - Token Bucket
        - Leaky Bucket
        - GCRA
        - N/A
    validations:
      required: true
